### ISSUE TITLE
Question about transfer learning format

### ISSUE THREAD

**Issue by jeffreyleifer** [wayneweiqiang/PhaseNet#35]
Hi,
Thank you for this project. 
I'm attempting to put my data-set in the correct format for transfer learning on the master branch.
I see in branch 1.0 there is a format specified in the README.md. 
But in the master branch's test_data.zip, the npz.csv contains many more fields than specified in the branch 1.0 README.md.

Should I use the format of the npz.csv from the test_data.zip or can I still use the format specified in branch 1.0

Cheers

**Comment by tt123890** [comment]
Hello, how did you ultimately solve it?
