### ISSUE TITLE
Format of prediction results

### ISSUE THREAD

**Issue by zhong-yy** [wayneweiqiang/PhaseNet#59]
Hi Dr, Zhu,
I noticed that the format of prediction results has been updated.The new format is
```
file_name      begin_time    station_id      phase_index      phase_time      phase_score      phase_type
```
The old format is
```
fname     t0      p_idx      p_prob      s_idx      s_prob
```

Is it still possible to output the old format in the latest version?

**Comment by wayneweiqiang** [comment]
Hi, thanks for the question. Yes, I recently updated the output format, because the old format is a bit hard to read. You can easily read the new format using pandas.read_csv. Then you can rename the column names to match the old format. Please let me know you have any suggestions or questions.

**Comment by zhong-yy** [comment]
> Hi, thanks for the question. Yes, I recently updated the output format, because the old format is a bit hard to read. You can easily read the new format using pandas.read_csv. Then you can rename the column names to match the old format. Please let me know you have any suggestions or questions.

Thank you. I have turned the output into the old format. By the way, what is the `station_id` used for? It is the same as the filename.

**Comment by wayneweiqiang** [comment]
For a mseed file, it contains station_id, so the station_id is different from file_name.

**Comment by zhong-yy** [comment]
> For a mseed file, it contains station_id, so the station_id is different from file_name.

Thank you, then I can just ignore the station_id
