### ISSUE TITLE
Picks.csv writing to a new line when a row becomes overfull

### ISSUE THREAD

**Issue by lennijusten** [wayneweiqiang/PhaseNet#6]
I placed the P & S probability threshold very low for a batch of .npz files I wanted to predict which cause PhaseNet to make a lot of picks. When the columns ts_prob and tp_prob became overfull, the csv didn't just expand the column width but made a new row where it appended the overfull lines.

I have attached the picks.csv. Here are the setting I ran PhaseNet with:

python PhaseNet/run.py --mode=pred --model_dir=PhaseNet/model/190703-214543 --data_dir=Dataset/NPZ --tp_prob=0.05 --ts_prob=0.05 --data_list=Dataset/waveform.csv --output_dir=PhaseNet/output --plot_figure --save_result --batch_size=30 --input_length=27001

[picks.csv.zip](https://github.com/wayneweiqiang/PhaseNet/files/4786917/picks.csv.zip)

**Comment by wayneweiqiang** [comment]
Thanks for reporting the bugs and sending the fix!  
If you want to view the activations for each data point, you can add the "--save_result" argument. It will save all the predicted probability sequences.
