### ISSUE TITLE
How can I present new data for training?

### ISSUE THREAD

**Issue by Grexilo** [wayneweiqiang/PhaseNet#60]
Hi, I was analyzing the data under  **PhaseNet/dataset/waveform_train**

For that purpose I just focus my attention to the file **data_reader.py** and I used the class DataReader_train.

So my first step was open the npz files under the dataset folder and I want to see how the event looks like.

Then when I use the DataReader_train class and I want to see how you class interact with the data I saw this.
![Original data from the npz file](https://user-images.githubusercontent.com/43388194/188911422-c9c6af02-8ca1-4d04-8679-c0b6650ba860.png)
![Data after DataReader_train class](https://user-images.githubusercontent.com/43388194/188911648-11462047-739f-4931-9dee-e6dc64fdfd72.png)

So, anyone knows how can I present new data for training?

**Comment by wayneweiqiang** [comment]
Hi, you can prepare new training data using the numpy.savez command. And you can follow the same format as the demo npz data. SeisBench also has more tutorials on model training: https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/03a_training_phasenet.ipynb
