### ISSUE TITLE
Training data with only with no S (`its`)

### ISSUE THREAD

**Issue by lvanderlaat** [wayneweiqiang/PhaseNet#8]
Hi, 

I am preparing my data to train. Some stations have only P arrivals picked. How does PhaseNet handle a `NaN` value at the `its` column? Is it possible to do this? Or is it imperative to have both `itp` and `its`?

Thank you very much

Leo

**Comment by wayneweiqiang** [comment]
Hi, 

Because PhaseNet is designed to predict probabilities of all  P, S, and noise. It needs both P and S labels. The missing its label will bias the training. If you have too many missing S picks, one alternative way to training separate models for P and S waves.

Thanks,
Weiqiang
